#!/bin/bash

### CONFIG ###
# TASKS_DIR		- dir where fetched tasks will be located
# COMPLETE_TASKS_DIR	- dir where finished tasks will be located

config_file="$HOME/.mash.conf"

BIN_DIR=$PWD/${0%/*};
source "$BIN_DIR/mash.functions"
source "$BIN_DIR/task_loader.sh"

if [ -f "$config_file" ]; then
	read_config "$config_file"

	validate_vars "$config_file"

	(
		cd "$TASKS_DIR" &&
		fetch_tasks &&
		[ $(ls -1 --file-type | grep -ciE '^[0-9a-f]{32}$') -gt 0 ] &&	# if there is tasks
		start_tasks $COMPLETE_TASKS_DIR
	)

else
	echo $config_file does not exist
fi

#fetch_tasks "$TASKS_DIR"
